#!/bin/bash

function rule() {
    echo "allow from $1 to any port $2"
}


curl -s https://www.cloudflare.com/ips-v4 > allowed
echo >> allowed
curl -s https://www.cloudflare.com/ips-v6 >> allowed

yes | /usr/sbin/ufw reset --force
/usr/sbin/ufw default allow

while read ip
do
    echo Allowing incoming port 80 from $ip
    /usr/sbin/ufw $(rule $ip 80)
done < allowed
rm allowed

/usr/sbin/ufw allow http
/usr/sbin/ufw allow https

/usr/sbin/ufw default deny
yes | ufw enable
